---
- name: Create required AWS security groups
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    rules: "{{ item.rules }}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ vpc_id }}"
  with_items: "{{ security_groups }}"

- name: Launch AWS instances
  ec2:
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    keypair: "{{ item.keypair }}"
    group: "{{ item.group }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.image }}"
    instance_tags: "{{ item.instance_tags }}"
    exact_count: "{{ item.exact_count }}"
    count_tag: "{{ item.count_tag }}"
    assign_public_ip: "{{ item.assign_public_ip }}"
    wait: yes
  register: ec2
  with_items: "{{ ec2_instances }}"