---
# set these parameters to control the region, keypair, and AMI that are launched
ec2_region: sa-east-1
vpc_id: vpc-0181902b8426da68f
vpc_subnet_id: subnet-0611885985817ae55
instances_keypair: evento
image_id: ami-b0b7e3dc

# security groups to be created
security_groups:
  - name: ssh
    desc: the security group for the jumphost
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  - name: web
    desc: the security group for the web server 
    rules:
      - proto: tcp
        from_port: "80"
        to_port: "80"
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "443"
        to_port: "443"
        cidr_ip: 0.0.0.0/0

  - name: db
    desc: the security group for the db server 
    rules:
      - proto: tcp
        from_port: "5432"
        to_port: "5432"
        cidr_ip: 0.0.0.0/0
  
# instances to launch be launched
ec2_instances:
  - instance_type: m1.small
    image: "{{ image_id }}"
    keypair: "{{ instances_keypair }}"
    assign_public_ip: true
    group: ['web', 'ssh'] 
    instance_tags: 
        Name: demo-web
    exact_count: 1
    count_tag: 
        Name: demo-web

  - instance_type: m1.small
    image: "{{ image_id }}"
    keypair: "{{ instances_keypair }}"
    assign_public_ip: true
    group: ['db', 'ssh'] 
    instance_tags: 
        Name: demo-db
    exact_count: 1 
    count_tag: 
        Name: demo-db
